### ISSUE TITLE
Quantization on imagenet takes several days on A100

### ISSUE THREAD

**Issue by LeeDongYeun** [ModelTC/TFMQ-DM#1]
Hi there,

I have been running your code on the ImageNet model using a single A100 GPU, and it has been taking several days to complete. I am curious if this is the expected duration for this task.

In your paper, you mentioned that training on LSUN256 took around 2 GPU hours. Could you please provide more details on how you measured the GPU hours? It would help me understand the performance expectations better.

Thank you for your assistance!

Best regards,
Dongyeun Lee

**Comment by Harahan** [comment]
Hi Dongyeun,

I guess you include data generation time in the duration. The logic of current data generation is to catch the input data of $t$ by denoising from $T$ to $t + 1$. **However, you can catch the input data of $T,\ldots, 0$ during one whole denoising pass, which performs nearly the same and only takes a few minutes.** BTW, you can also directly employ data from Q-Diffusion. 

We measure the GPU time employing the method within bold-black words, and most of the experiments conducted by this method to save time. The current open-source code is our initial version.
