### ISSUE TITLE
First & Last layer full-precision?

### ISSUE THREAD

**Issue by seung-hoon-lee** [ModelTC/TFMQ-DM#11]
Hi, thanks for sharing your awesome work!

However, I guess there is some confusion in the sentence "we maintain the input and output layers of the model in full precision." in the paper.
I understand that traditional settings set the first & last layers as fp.

Nevertheless, the code you provided doesn’t seem to set only the first and the last layer to FP, but rather the **first two layers** (modules[2], modules[3])and last layer(modules[-1]). Is there a reason for setting the second layer(modules[3]) as fp??

 
![image](https://github.com/user-attachments/assets/1a48eab1-14f1-4f7f-b370-d2146f1634c7)

**Comment by Harahan** [comment]
Layer 0 and Layer 2 have different inputs,so we consider they are both the first layers in the model.
