### ISSUE TITLE
How to test inference latency on cpu device?

### ISSUE THREAD

**Issue by vokkko** [ModelTC/TFMQ-DM#2]
It's a nice work for DM quantization. I'm confused to the latency testing on device, could you please more details ?

**Comment by Harahan** [comment]
Hi, thanks for your appreciation. We evaluate the speedup with our modified Intel's OpenVino framework. It's not very hard to do the job, e.g., exporting the fake quantized Pytorch model to the right format, and switching activation quantization parameters every single time-step.

**Comment by vokkko** [comment]
Thanks !
