### ISSUE TITLE
Can this receipt run on the A100 only with 40 G memory?

### ISSUE THREAD

**Issue by PeiyanFlying** [ModelTC/TFMQ-DM#3]
Thank you so much for this wonderful and valuable work. I have run the code on one A100  with 40 G memory, and it reports 'out of memory.' I have two A100 cards. Can you give me some suggestions on how to deal with this memory issue? Looking forward to your feedback.

**Comment by Harahan** [comment]
Hi, thanks for your appreciation. You can try the following approaches to reduce memory:
*  Reduce the batch size for the quantization process. BTW, it may affect the model performance.  
*  Do not employ ``keep_gpu`` in https://github.com/ModelTC/TFMQ-DM/blob/1068e8aa0aa477a59a8afd01a99a906b0f88a8f2/quant/data_utill.py#L39. However, this may significantly slow down the whole process.
