### ISSUE TITLE
Caliberate with Stable Diffusion

### ISSUE THREAD

**Issue by csguoh** [ModelTC/TFMQ-DM#4]
Hi,

Sorry to bother you. I notice that you have use the text prompts json from COCO dataset for cali_data generation. Since there are various versions of COCO, I want to know which specific dataset should I download? btw, what gpus should be used for calibration with the SD model?

Thx.

**Comment by Harahan** [comment]
Hi,

We employ COCO 2014 with one H800 80G GPU for quantizing Stable Diffusion.
