### ISSUE TITLE
How to calculate FID？

### ISSUE THREAD

**Issue by Seline02** [ModelTC/TFMQ-DM#7]
Hello, thank you for your excellent work. 

I have a question about the process of calculating FID and FIDs.
For dataset LSUN-Bedrooms, I use pre-calculated reference batch from [https://github.com/openai/guided-diffusion/tree/main/evaluations](url) directly. But I wonder how to get reference batches from LSUN-Churches, CelebA-HQ and FFHQ? And how many images did you sample to make a reference batch?

Thanks!

**Comment by Harahan** [comment]
Hi,

I employ the whole training set. you can refer to the procedure to get the reference batch following https://github.com/Xiuyu-Li/q-diffusion/issues/5

**Comment by Seline02** [comment]
Thanks a lot!

**Comment by msz12345** [comment]
> Hello, thank you for your excellent work.
> 
> I have a question about the process of calculating FID and FIDs. For dataset LSUN-Bedrooms, I use pre-calculated reference batch from [https://github.com/openai/guided-diffusion/tree/main/evaluations](url) directly. But I wonder how to get reference batches from LSUN-Churches, CelebA-HQ and FFHQ? And how many images did you sample to make a reference batch?
> 
> Thanks!

Hi , I am also confused about the where the reference batchs of Lsun Churchs256 are, Did you find it or generate it by yourself?  I need your help, your help is precious to me and I am really appreciate it, Thanks!
