### ISSUE TITLE
Question about experiment results

### ISSUE THREAD

**Issue by Seline02** [ModelTC/TFMQ-DM#8]
Hello, thank you for your excellent work. I'm sorry to bother you again.

The caption of Table 3 in your paper is about "LDM-8 on ImageNet 256x256", but I notice that the  result of PTQD method in Table 3 is almost the same with PTQD's result on model LDM-4. So I want to figure out which model you quantized, LDM-4 or LDM-8.

Thanks a lot!

**Comment by Harahan** [comment]
Yes，it is LDM-4.
