### ISSUE TITLE
Some Questions about Activation Quantization

### ISSUE THREAD

**Issue by IC-Yuan** [ModelTC/TFMQ-DM#9]
Hi,
Thanks for this work!

In the paper, it is mentioned: "In activation quantization, we utilize EMA [16] to estimate the ranges of activations with a mini-batch size of 16 on all models." I was pleasantly surprised to see an activation handling approach different from the BRECQ paradigm. However, in the code, I still see the same approach used as in the BRECQ paradigm. I would like to know if EMA is used in the code?

**Comment by Harahan** [comment]
EMA is employed.https://github.com/ModelTC/TFMQ-DM/blob/c4de88c300a2935cc82d487f2fa3f95ef4253fab/quant/calibration.py#L128

**Comment by IC-Yuan** [comment]
Thank you very much for your reply!

This work indeed uses the EMA method. However, in the original paper, EMA is used to gradually adjust the activation range during the weight training process, while in this work, the adjustment is only performed during inference. Therefore, the activation range will depend on `act_range_momentum` and the order of the input data. Of course, this is indeed a different approach from the min-max method. Anyway, this is definitely an interesting idea. Thank you for the reply and for sharing the code!

Thanks again!
